- name: install docker
  hosts: production
  user: ubuntu
  become: true
  tasks:

  tasks:
  - name: 1. Update APT Package Manager
    shell:
      cmd: sudo apt-get update
  - name: 2. Uninstall the unscd package
    apt:
      update_cache: yes
      name: unscd
      state: absent
  - name: 3. Install dependency packages
    apt:
      name={{ item }}
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: 4. Get APT Key
    shell:
      cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: 5. Confirm Fingerprint
    shell:
      cmd: sudo apt-key fingerprint 0EBFCD88

  - name: 6. Add APT Repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

  - name: 7. Update Package Manager
    apt:
      update_cache: yes

  - name: 8. Install Docker packages
    apt:
      name={{ item }}
    with_items:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: 9. set permissions via commands
    become: no
    shell:
      cmd: sudo groupadd docker
      cmd: sudo usermod -aG docker $USER
      cmd: sudo addgroup --system docker
      cmd: sudo adduser $USER docker
      cmd: newgrp docker
      cmd: groups
    register: shell_output

  # the above task hangs without this task (no idea why)
  - name: debug 
    debug: var=shell_output

  - name: 12. Output docker version
    shell:
      cmd: docker version