- name: deploy & update via kubernetes (via ansible-tags)
  hosts: production
  become: yes
  become_user: ubuntu
  user: ubuntu # SSH appears to fail if this attribute doesn't exist, but I'm unable to find it on ansible docs
  gather_facts: yes
  tasks:
  # will run this once manually then Jenkins will run the --tags "update"
  - name: Start Minikube ( ASSUMES MINIKUBE IS NOT RUNNING & DEPLOYMENT DOES NOT EXIST - WILL FAIL OTHERWISE)
    # I swear this worked yesterday :| , Minikube no longer seems to be starting 
    # hence the kubectl : Unable to connect to the server : dial tcp <ip>: connect: no route to host
    shell:
      cmd: minikube start driver=Docker
    #shell:
    #  cmd: ssh ubuntu@54.204.28.63 'minikube start driver=Docker'

  #- name: Create + scale depl
  #  raw: kubectl create deployment nodeapp --image=hub.docker.com/r/devopsbh/nodeapp
    
  - name: create deployment 
    shell:
      cmd: kubectl create deployment nodeapp --image=devopsbh/nodeapp

  # the Kubectl deployment takes sometime to be ready (i.e. spin up) so I don't think unready deployments can be exposed 
  - name: Pause for 1 minute to let deployment get ready 
    ansible.builtin.pause:
      minutes: 1

  - name: Expose deployment as a service 
    shell:
      cmd: kubectl expose deployment/nodeapp --type="NodePort" --port 8080 --name node-port-service
      cmd: kubectl scale deployments/nodeapp --replicas=4
      #cmd: ssh ubuntu@54.204.28.63 'kubectl create deployment nodeapp --image=hub.docker.com/r/devopsbh'
    tags: [deploy]

  - meta: end_play

  #- name: Expose 
    #become_user: root
    #debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]
    #debug: var=hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')[2]
  #  shell: 
  #    cmd: export IP_ADDRESS=$(dig +short txt ch whoami.cloudflare @1.0.0.1)
  #    cmd: echo "ADDRES". $IP_ADDRESS
  #    cmd: kubectl expose nodeapp --type="NodePort" --port $IP_ADDRESS:8080 --name node-port-service
  #  tags: [deploy]

  #- meta: end_play
  
  # JENKINS WILL ONLY RUN THIS 
  - name: Rolling updates 
    shell: 
      cmd: kubectl set image deployments/nodeapp nodeapp=devopsbh/nodeapp:latest
      cmd: kubectl rollout status deployments/nodeapp
    tags: [update]

  # the above task hangs without this task (no idea why)
  - name: debug 
    debug: var=shell_output